# Generated by Django 4.1.2 on 2024-02-05 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clasegrupo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="claseparticular",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 4, 20, 18, 28, 362264)
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pagos",
            name="fecha_pago",
            field=models.DateField(
                default=datetime.datetime(2024, 2, 4, 20, 18, 28, 362264)
            ),
        ),
        migrations.AlterField(
            model_name="pagos",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
