# Generated by Django 4.1.2 on 2024-02-05 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0002_alter_clasegrupo_id_alter_claseparticular_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 4, 20, 48, 53, 19426)
            ),
        ),
        migrations.AlterField(
            model_name="pagos",
            name="fecha_pago",
            field=models.DateField(
                default=datetime.datetime(2024, 2, 4, 20, 48, 53, 19427)
            ),
        ),
    ]
