# Generated by Django 4.1.2 on 2024-02-05 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="fecha_registro",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 4, 20, 18, 28, 362264)
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
