# Generated by Django 4.1.2 on 2024-02-05 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actors", "0002_alter_cliente_fecha_registro_alter_cliente_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="dni",
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="fecha_registro",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 4, 20, 48, 53, 19426)
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="dni",
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="telefono",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
