# Generated by Django 4.1.2 on 2024-02-05 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actors", "0003_alter_cliente_dni_alter_cliente_fecha_registro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="fecha_nacimiento",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="fecha_registro",
            field=models.DateField(
                default=datetime.datetime(2024, 2, 4, 21, 1, 6, 35902)
            ),
        ),
    ]
