# Generated by Django 4.1.2 on 2024-02-05 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actors", "0004_alter_cliente_fecha_nacimiento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="fecha_registro",
            field=models.DateField(default=datetime.date(2024, 2, 4)),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="authorization",
            field=models.SmallIntegerField(null=True),
        ),
    ]
