# Generated by Django 4.1.2 on 2024-02-23 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0007_cliente_email_empleado_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='email',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateField(default=datetime.date(2024, 2, 22)),
        ),
    ]
